### ISSUE TITLE
How can i configure it to get cover images from Last.fm?

### ISSUE THREAD

**Issue by fmarzocca** [mopidy/mopidy-local-images#28]
Hi,

how can I configure mopidy-local-images in order to get images from Last.fm?

base_uri = ????

**Comment by kingosticks** [comment]
> allows Web clients access to album art embedded in local media files

This extension has nothing to do with last.fm. That a parameter is documented in the readme.

**Comment by fmarzocca** [comment]
```
# the base URI for images; change this if you want to serve images
# using an alternative Web server, or when accessing Mopidy through a
# reverse proxy
base_uri = /images/
```

If you can call these lines as "documentation", I am the Pope!

**Comment by jodal** [comment]
Please refrain from negative comments and instead suggest an improvement to the "documentation".

**Comment by fmarzocca** [comment]
Yes, sorry. I would have suggested improvements for sure, if only documentation was clear to me! But maybe it's a problem of mine. Sorry again. Never mind.

**Comment by tkem** [comment]
@fmarzocca: Your Holiness, 
as the README states quite prominently in its first sentence,
```
Mopidy-Local-Images is a Mopidy local library and Web extension that allows Web clients access to album art embedded in local media files.
```
The key word here is _embedded_., i.e. images stored in your local MP3/FLAC/etc. files.
There is no support for retrieving album art from Last.fm or other online services. Why? Because _clients_ (Web extensions, apps, etc.) already can do this, and usually can (or at least, could) do a better job at this than a Mopidy backend extension from a UX point of view, at least IMHO. So this extension's main goal is to extract images _embedded_ in your local music files (or stored in the local filesystem alongside them) and making them available to Mopidy clients.

**Comment by fmarzocca** [comment]
@tkem Thank you son. Very clear and detailed motivation! :-)

**Comment by tkem** [comment]
@fmarzocca: Bad vibes settled now, you are more than welcome ;-)
Regarding the documentation for the config settings (which, of course, could _always_ be improved): 99% of users won't need them, IMHO, and for the rest it should either be sufficient _as-is_, or things would have to be worked out in personal communication, anyway.
That particular setting, `base_uri`, only makes sense if you are running Mopidy _behind_ another Web server (Apache, nginx, etc.), e.g. to use SSL or some form of user authentication. _Then_ you'd probably have to set this.

**Comment by fmarzocca** [comment]
> That particular setting, `base_uri`, only makes sense if you are running Mopidy _behind_ another Web server (Apache, nginx, etc.), e.g. to use SSL or some form of user authentication. _Then_ you'd probably have to set this.

Yes, now it’s clear. This should have been the very first answer, so we all would have saved time. 
Thank you very much again.
